project:
  type: website
  output-dir: ../_site/nl
  resources:
    - assets

lang: nl

website:
  description: "Etiënne Thomassen"
  site-url: https://etiennethomassen.nl
  title: "Etiënne Thomassen"
  site-path: /nl/
  favicon: https://etiennethomassen.nl/favicon.ico
  navbar:
    right:
      - text: Notities
        href: /posts/
      - text: Publicaties
        href: /publications/
      - text: Over
        href: /about.html
      - text: EN
        href: ../en/

format:
  html:
    link-external-icon: true
    theme:
      - cosmo
      - brand
      - assets/scss/custom.scss
    css:
      - assets/fonts/gentium/stylesheet.css
      - assets/fonts/aller/stylesheet.css
      - assets/fonts/entypo-social/stylesheet.css
      - assets/fonts/inter/stylesheet.css
      - assets/fonts/gentium_plus/stylesheet.css
      - assets/css/styles.css
    include-in-header: 
      - assets/incl/header_includes.html
      - assets/incl/hreflang.html
    include-after-body:
      - assets/incl/footer.html
      - assets/incl/simple_analytics.html

